
import React from 'react';

export default function PrintableBill({ items, totalSugar, totalCost, userName }) {
  return (
    <div className="hidden print:block">
      <div className="p-8 bg-white">
        <div className="text-center mb-8">
          <h1 className="text-4xl font-bold text-purple-900 mb-2">Sugar Bill™</h1>
          <p className="text-gray-600">Generated on {new Date().toLocaleDateString()}</p>
          {userName && <p className="text-gray-600">For: {userName}</p>}
        </div>
        
        <table className="w-full mb-8">
          <thead>
            <tr className="border-b-2 border-gray-300">
              <th className="text-left py-3 px-4">Item</th>
              <th className="text-center py-3 px-4">Quantity</th>
              <th className="text-center py-3 px-4">Sugar (g)</th>
              <th className="text-right py-3 px-4">Cost (₹)</th>
              <th className="text-right py-3 px-4">Total Sugar (g)</th>
              <th className="text-right py-3 px-4">Total Cost (₹)</th>
            </tr>
          </thead>
          <tbody>
            {items.filter(item => item.quantity > 0).map((item) => (
              <tr key={item.id} className="border-b border-gray-200">
                <td className="py-3 px-4">{item.name}</td>
                <td className="text-center py-3 px-4">{item.quantity}</td>
                <td className="text-center py-3 px-4">{item.sugar}</td>
                <td className="text-right py-3 px-4">{item.cost.toFixed(2)}</td>
                <td className="text-right py-3 px-4 font-semibold">{(item.sugar * item.quantity).toFixed(1)}</td>
                <td className="text-right py-3 px-4 font-semibold">{(item.cost * item.quantity).toFixed(2)}</td>
              </tr>
            ))}
          </tbody>
          <tfoot>
            <tr className="border-t-2 border-gray-400 font-bold">
              <td colSpan="4" className="py-4 px-4 text-right">TOTAL:</td>
              <td className="py-4 px-4 text-right text-orange-700 text-xl">{totalSugar}g</td>
              <td className="py-4 px-4 text-right text-green-700 text-xl">₹{totalCost}</td>
            </tr>
          </tfoot>
        </table>
        
        <div className="mt-8 pt-4 border-t border-gray-300 text-sm text-gray-600">
          <p>💡 Recommended daily sugar intake: ~25-50g for adults</p>
          <p className="mt-2">This bill was generated by Sugar Bill App</p>
          <p className="mt-4 text-center text-gray-500">© Sugar Smart</p>
        </div>
      </div>
    </div>
  );
}
